language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install -r requirements.txt
    - python setup.py install
before_script:
    - pip install pprint
    - pip install python-coveralls
    - pip install coverage
script:
    - coverage tests.py
after_success:
    - coveralls
